;//========================================================================================================
;//  Basically, all of files downloaded from my website can be modified or redistributed for any purpose.
;//  It is my honor to share my interesting to everybody.
;//  If you find any illeage content out from my website, please contact me firstly.
;//  I will remove all of the illeage parts.
;//  Thanks :)
;//  
;//  Steward Fu
;//  g9313716@yuntech.edu.tw
;//  https://steward-fu.github.io/website/index.htm
;//========================================================================================================*/
;//typedef VOID (*WDFFUNC) (VOID);
;//extern WDFFUNC WdfFunctions [];
WDFFUNC typedef proto WDFAPI
PWDFFUNC typedef ptr WDFFUNC
extern WdfFunctions:proc
